// @meta triton=true
// Auto-generated by Triton WebGPU Backend
// Kernel: silu_mul_fused_kernel
// Workgroup size: 128 (4 warps x 32 threads)

@group(0) @binding(0) var<storage, read> buf0: array<f32>;  // GateUp
@group(0) @binding(1) var<storage, read_write> buf1: array<f32>;  // Out

struct Params {
    N: i32,
};
@group(0) @binding(2) var<storage, read> params: Params;

@compute @workgroup_size(128)
fn main(
    @builtin(workgroup_id) _wg_id: vec3<u32>,
    @builtin(local_invocation_id) _lid: vec3<u32>,
    @builtin(num_workgroups) _num_wg: vec3<u32>,
) {
    let v6: i32 = i32(_wg_id.x);
    let v7: i32 = v6 * 128;
    let v8: i32 = i32(_lid.x);
    let v9: i32 = v8 & 127;
    let v10: i32 = i32(u32(v9) % u32(32));
    let v11: i32 = i32(_lid.x);
    let v12: i32 = i32(u32(v11) / u32(32));
    let v13: i32 = v10 << u32(0);
    let v14: i32 = 0 | v13;
    let v15: i32 = v12 << u32(5);
    let v16: i32 = v14 | v15;
    let v17: i32 = v16 & 127;
    let v18: i32 = i32(u32(v17) >> u32(0));
    let v19: i32 = v18 | 0;
    let v20: i32 = 0 ^ v19;
    let v21: i32 = v20 ^ 0;
    let v22: i32 = v21 + 0;
    let v23: i32 = v7 + v22;
    let v24: bool = v23 < params.N;
    let v26: f32 = buf0[u32(v23)];
    let v27: f32 = select(f32(0.0), v26, v24);
    let v30: f32 = buf0[u32((params.N + v23))];
    let v31: f32 = select(f32(0.0), v30, v24);
    let v32: f32 = f32(0.0) - v27;
    let v33: f32 = exp(v32);
    let v34: f32 = v33 + f32(1.0);
    let v35: f32 = v27 / v34;
    let v37: f32 = v35 * v31;
    let v38: f32 = select(f32(0), v37, v24);
    if v24 { buf1[u32(v23)] = v38; }
}
