// @meta triton=true
enable f16;
enable subgroups;

// Auto-generated by Triton WebGPU Backend
// Kernel: fused_qknorm_rope_qkv_kernel
// Workgroup size: 128 (4 warps x 32 threads)

var<workgroup> _smem: array<i32, 4>;

@group(0) @binding(0) var<storage, read> buf0: array<f32>;  // QKV
@group(0) @binding(1) var<storage, read_write> buf1: array<f32>;  // Q_out
@group(0) @binding(2) var<storage, read_write> buf2: array<f16>;  // K_cache
@group(0) @binding(3) var<storage, read_write> buf3: array<f16>;  // V_cache
@group(0) @binding(4) var<storage, read> buf4: array<f32>;  // CosTable
@group(0) @binding(5) var<storage, read> buf5: array<f32>;  // SinTable
@group(0) @binding(6) var<storage, read> buf6: array<f32>;  // NormQ
@group(0) @binding(7) var<storage, read> buf7: array<f32>;  // NormK

struct Params {
    n_head: i32,
    q_size: i32,
    kv_size: i32,
    pos: i32,
    half_rot: i32,
    cache_offset: i32,
    eps: f32,
};
@group(0) @binding(8) var<storage, read> params: Params;

@compute @workgroup_size(128)
fn main(
    @builtin(workgroup_id) _wg_id: vec3<u32>,
    @builtin(local_invocation_id) _lid: vec3<u32>,
    @builtin(num_workgroups) _num_wg: vec3<u32>,
) {
    let v18: i32 = i32(_wg_id.x);
    let v19: i32 = i32(_lid.x);
    let v20: i32 = v19 & 127;
    let v21: i32 = i32(u32(v20) % u32(32));
    let v22: i32 = i32(_lid.x);
    let v23: i32 = i32(u32(v22) / u32(32));
    let v24: i32 = v21 << u32(0);
    let v25: i32 = 0 | v24;
    let v26: i32 = v23 << u32(5);
    let v27: i32 = v25 | v26;
    let v28: i32 = v27 & 127;
    let v29: i32 = i32(u32(v28) >> u32(0));
    let v30: i32 = v29 | 0;
    let v31: i32 = 0 ^ v30;
    let v32: i32 = v31 ^ 0;
    let v33: i32 = v32 + 0;
    let v34: bool = v18 < params.n_head;
    let v35: i32 = v18 - params.n_head;
    let v36: i32 = v18 * 128;
    let v37: i32 = v35 * 128;
    let v38: i32 = params.q_size + v37;
    let v39: i32 = select(v38, v36, v34);
    let v42: f32 = buf0[u32((v39 + v33))];
    let v43: f32 = v42 * v42;
    let v44: i32 = bitcast<i32>(v43);
    let v45: i32 = subgroupShuffleXor(v44, u32(16));
    let v46: f32 = bitcast<f32>(v45);
    let v47: f32 = v43 + v46;
    let v48: i32 = bitcast<i32>(v47);
    let v49: i32 = subgroupShuffleXor(v48, u32(8));
    let v50: f32 = bitcast<f32>(v49);
    let v51: f32 = v47 + v50;
    let v52: i32 = bitcast<i32>(v51);
    let v53: i32 = subgroupShuffleXor(v52, u32(4));
    let v54: f32 = bitcast<f32>(v53);
    let v55: f32 = v51 + v54;
    let v56: i32 = bitcast<i32>(v55);
    let v57: i32 = subgroupShuffleXor(v56, u32(2));
    let v58: f32 = bitcast<f32>(v57);
    let v59: f32 = v55 + v58;
    let v60: i32 = bitcast<i32>(v59);
    let v61: i32 = subgroupShuffleXor(v60, u32(1));
    let v62: f32 = bitcast<f32>(v61);
    let v63: f32 = v59 + v62;
    let v64: i32 = i32(_lid.x);
    let v65: i32 = v64 & 127;
    let v66: i32 = i32(u32(v65) % u32(32));
    let v67: i32 = i32(_lid.x);
    let v68: i32 = i32(u32(v67) / u32(32));
    let v69: i32 = v66 << u32(0);
    let v70: i32 = 0 | v69;
    let v71: i32 = v68 << u32(5);
    let v72: i32 = v70 | v71;
    let v73: i32 = v72 & 96;
    let v74: i32 = i32(u32(v73) >> u32(3));
    let v75: i32 = 0 | v74;
    let v76: i32 = 0 ^ v75;
    let v77: i32 = v76 ^ 0;
    let v78: i32 = v77 ^ 0;
    let v79: i32 = v78 + 0;
    _smem[u32(v79) >> 2u] = bitcast<i32>(v63);
    workgroupBarrier();
    let v83: i32 = i32(_lid.x);
    let v84: i32 = v83 & 127;
    let v85: i32 = i32(u32(v84) % u32(32));
    let v86: i32 = i32(_lid.x);
    let v87: i32 = i32(u32(v86) / u32(32));
    let v88: i32 = v85 << u32(0);
    let v89: i32 = 0 | v88;
    let v90: i32 = v87 << u32(5);
    let v91: i32 = v89 | v90;
    let v92: i32 = v91 & 3;
    let v93: i32 = v92 << u32(2);
    let v94: i32 = v93 | 0;
    let v95: i32 = 0 ^ v94;
    let v96: i32 = v95 ^ 0;
    let v97: i32 = v96 ^ 0;
    let v98: i32 = v97 + 0;
    let v100: f32 = bitcast<f32>(_smem[u32(v98) >> 2u]);
    let v103: i32 = bitcast<i32>(v100);
    let v104: i32 = subgroupShuffleXor(v103, u32(2));
    let v105: f32 = bitcast<f32>(v104);
    let v106: f32 = v100 + v105;
    let v107: i32 = bitcast<i32>(v106);
    let v108: i32 = subgroupShuffleXor(v107, u32(1));
    let v109: f32 = bitcast<f32>(v108);
    let v110: f32 = v106 + v109;
    let v111: f32 = v110 / f32(128.0);
    let v112: f32 = v111 + params.eps;
    let v113: f32 = sqrt(v112);
    let v114: f32 = f32(1.0) / v113;
    let v116: f32 = buf6[u32(v33)];
    let v118: f32 = buf7[u32(v33)];
    let v119: f32 = select(v118, v116, v34);
    let v120: f32 = v42 * v114;
    let v121: f32 = v120 * v119;
    let v122: i32 = v33 % params.half_rot;
    let v123: i32 = params.half_rot * 2;
    let v124: bool = v33 < v123;
    let v125: i32 = params.pos * params.half_rot;
    let v128: f32 = buf4[u32((v125 + v122))];
    let v129: f32 = select(f32(1.0), v128, v124);
    let v132: f32 = buf5[u32((v125 + v122))];
    let v133: f32 = select(f32(0.0), v132, v124);
    let v134: bool = v33 < params.half_rot;
    let v135: f32 = select(f32(1.0), f32(-1.0), v134);
    let v136: i32 = v33 + params.half_rot;
    let v137: i32 = v33 - params.half_rot;
    let v138: i32 = select(v137, v136, v134);
    let v139: i32 = select(v33, v138, v124);
    let v141: f32 = buf0[u32((v39 + v139))];
    let v143: f32 = buf6[u32(v139)];
    let v145: f32 = buf7[u32(v139)];
    let v146: f32 = select(v145, v143, v34);
    let v147: f32 = v141 * v114;
    let v148: f32 = v147 * v146;
    let v149: f32 = v121 * v129;
    let v150: f32 = v135 * v148;
    let v151: f32 = v150 * v133;
    let v152: f32 = v149 + v151;
    let v153: f32 = select(v121, v152, v124);
    let v156: f32 = select(f32(0), v153, v34);
    if v34 { buf1[u32((v36 + v33))] = v156; }
    let v157: i32 = select(0, 1, v34);
    let v158: bool = v157 == 0;
    let v162: f32 = select(f32(0), v153, v158);
    if v158 { buf2[u32(((params.cache_offset + v37) + v33))] = f16(v162); }
    let v163: i32 = params.q_size + params.kv_size;
    let v164: i32 = v163 + v37;
    let v167: f32 = buf0[u32((v164 + v33))];
    let v168: f32 = select(f32(0.0), v167, v158);
    let v172: f32 = select(f32(0), v168, v158);
    if v158 { buf3[u32(((params.cache_offset + v37) + v33))] = f16(v172); }
}
