#pragma once
/**
 * json_parser.h — Minimal JSON parser for manifest.json.
 *
 * Supports: objects, arrays, strings, numbers, booleans, null.
 * Not a full JSON parser — tuned for the specific manifest format
 * generated by compile_model.py. For production, use nlohmann/json.
 */

#include <cstdint>
#include <map>
#include <string>
#include <variant>
#include <vector>

struct JsonValue;
using JsonObject = std::map<std::string, JsonValue>;
using JsonArray = std::vector<JsonValue>;

struct JsonValue {
    std::variant<std::nullptr_t, bool, double, std::string,
                 JsonArray, JsonObject> data;

    bool is_null()   const { return std::holds_alternative<std::nullptr_t>(data); }
    bool is_bool()   const { return std::holds_alternative<bool>(data); }
    bool is_number() const { return std::holds_alternative<double>(data); }
    bool is_string() const { return std::holds_alternative<std::string>(data); }
    bool is_array()  const { return std::holds_alternative<JsonArray>(data); }
    bool is_object() const { return std::holds_alternative<JsonObject>(data); }

    bool              as_bool()   const { return std::get<bool>(data); }
    double            as_number() const { return std::get<double>(data); }
    int               as_int()    const { return (int)std::get<double>(data); }
    uint32_t          as_uint()   const { return (uint32_t)std::get<double>(data); }
    const std::string& as_string() const { return std::get<std::string>(data); }
    const JsonArray&  as_array()  const { return std::get<JsonArray>(data); }
    const JsonObject& as_object() const { return std::get<JsonObject>(data); }

    // Convenience accessors
    const JsonValue& operator[](const std::string& key) const {
        return std::get<JsonObject>(data).at(key);
    }
    const JsonValue& operator[](size_t idx) const {
        return std::get<JsonArray>(data).at(idx);
    }
    size_t size() const {
        if (is_array()) return as_array().size();
        if (is_object()) return as_object().size();
        return 0;
    }
    bool has(const std::string& key) const {
        if (!is_object()) return false;
        return as_object().count(key) > 0;
    }
};

/// Parse a JSON string into a JsonValue. Dies on error.
JsonValue json_parse(const std::string& text);
