enable subgroups;

// Auto-generated by Triton WebGPU Backend
// Kernel: add_rms_norm_loop_kernel
// Workgroup size: 128 (4 warps x 32 threads)

var<workgroup> _smem: array<i32, 4>;

@group(0) @binding(0) var<storage, read_write> buf0: array<f32>;  // X
@group(0) @binding(1) var<storage, read> buf1: array<f32>;  // Residual
@group(0) @binding(2) var<storage, read_write> buf2: array<f32>;  // Y
@group(0) @binding(3) var<storage, read> buf3: array<f32>;  // W
@group(0) @binding(4) var<storage, read_write> buf4: array<f32>;  // Rstd

struct Params {
    stride: i32,
    N: i32,
    eps: f32,
};
@group(0) @binding(5) var<storage, read> params: Params;

@compute @workgroup_size(128)
fn main(
    @builtin(workgroup_id) _wg_id: vec3<u32>,
    @builtin(local_invocation_id) _lid: vec3<u32>,
    @builtin(num_workgroups) _num_wg: vec3<u32>,
) {
    let v11: i32 = i32(_wg_id.x);
    let v12: i32 = params.N + 127;
    let v13: i32 = v12 / 128;
    var v15: i32 = 0;
    var v16_0: f32 = f32(0);
    loop {
        let v17: bool = v15 < v13;
        if !v17 { break; }
        let v19: i32 = v15 * 128;
        let v20: i32 = i32(_lid.x);
        let v21: i32 = v20 & 127;
        let v22: i32 = i32(u32(v21) % u32(32));
        let v23: i32 = i32(_lid.x);
        let v24: i32 = i32(u32(v23) / u32(32));
        let v25: i32 = v22 << u32(0);
        let v26: i32 = 0 | v25;
        let v27: i32 = v24 << u32(5);
        let v28: i32 = v26 | v27;
        let v29: i32 = v28 & 127;
        let v30: i32 = i32(u32(v29) >> u32(0));
        let v31: i32 = v30 | 0;
        let v32: i32 = 0 ^ v31;
        let v33: i32 = v32 ^ 0;
        let v34: i32 = v33 + 0;
        let v35: i32 = v19 + v34;
        let v36: bool = v35 < params.N;
        let v37: i32 = v11 * params.stride;
        let v40: f32 = buf0[u32((v37 + v35))];
        let v41: f32 = select(f32(0.0), v40, v36);
        let v44: f32 = buf1[u32((v37 + v35))];
        let v45: f32 = select(f32(0.0), v44, v36);
        let v46: f32 = v41 + v45;
        let v47: f32 = select(f32(0), v46, v36);
        if v36 { buf0[u32((v37 + v35))] = v47; }
        let v48: f32 = v46 * v46;
        let v50: f32 = v16_0 + v48;
        let v52: i32 = v15 + 1;
        v15 = v52;
        v16_0 = v50;
    }
    let v55: i32 = bitcast<i32>(v16_0);
    let v56: i32 = subgroupShuffleXor(v55, u32(16));
    let v57: f32 = bitcast<f32>(v56);
    let v58: f32 = v16_0 + v57;
    let v59: i32 = bitcast<i32>(v58);
    let v60: i32 = subgroupShuffleXor(v59, u32(8));
    let v61: f32 = bitcast<f32>(v60);
    let v62: f32 = v58 + v61;
    let v63: i32 = bitcast<i32>(v62);
    let v64: i32 = subgroupShuffleXor(v63, u32(4));
    let v65: f32 = bitcast<f32>(v64);
    let v66: f32 = v62 + v65;
    let v67: i32 = bitcast<i32>(v66);
    let v68: i32 = subgroupShuffleXor(v67, u32(2));
    let v69: f32 = bitcast<f32>(v68);
    let v70: f32 = v66 + v69;
    let v71: i32 = bitcast<i32>(v70);
    let v72: i32 = subgroupShuffleXor(v71, u32(1));
    let v73: f32 = bitcast<f32>(v72);
    let v74: f32 = v70 + v73;
    let v75: i32 = i32(_lid.x);
    let v76: i32 = v75 & 127;
    let v77: i32 = i32(u32(v76) % u32(32));
    let v78: i32 = i32(_lid.x);
    let v79: i32 = i32(u32(v78) / u32(32));
    let v80: i32 = v77 << u32(0);
    let v81: i32 = 0 | v80;
    let v82: i32 = v79 << u32(5);
    let v83: i32 = v81 | v82;
    let v84: i32 = v83 & 96;
    let v85: i32 = i32(u32(v84) >> u32(3));
    let v86: i32 = 0 | v85;
    let v87: i32 = 0 ^ v86;
    let v88: i32 = v87 ^ 0;
    let v89: i32 = v88 ^ 0;
    let v90: i32 = v89 + 0;
    _smem[u32(v90) >> 2u] = bitcast<i32>(v74);
    workgroupBarrier();
    let v94: i32 = i32(_lid.x);
    let v95: i32 = v94 & 127;
    let v96: i32 = i32(u32(v95) % u32(32));
    let v97: i32 = i32(_lid.x);
    let v98: i32 = i32(u32(v97) / u32(32));
    let v99: i32 = v96 << u32(0);
    let v100: i32 = 0 | v99;
    let v101: i32 = v98 << u32(5);
    let v102: i32 = v100 | v101;
    let v103: i32 = v102 & 3;
    let v104: i32 = v103 << u32(2);
    let v105: i32 = v104 | 0;
    let v106: i32 = 0 ^ v105;
    let v107: i32 = v106 ^ 0;
    let v108: i32 = v107 ^ 0;
    let v109: i32 = v108 + 0;
    let v111: f32 = bitcast<f32>(_smem[u32(v109) >> 2u]);
    let v114: i32 = bitcast<i32>(v111);
    let v115: i32 = subgroupShuffleXor(v114, u32(2));
    let v116: f32 = bitcast<f32>(v115);
    let v117: f32 = v111 + v116;
    let v118: i32 = bitcast<i32>(v117);
    let v119: i32 = subgroupShuffleXor(v118, u32(1));
    let v120: f32 = bitcast<f32>(v119);
    let v121: f32 = v117 + v120;
    let v122: f32 = f32(params.N);
    let v123: f32 = v121 / v122;
    let v124: f32 = v123 + params.eps;
    let v125: f32 = sqrt(v124);
    let v126: f32 = f32(1.0) / v125;
    var v128: i32 = 0;
    loop {
        let v129: bool = v128 < v13;
        if !v129 { break; }
        let v131: i32 = v128 * 128;
        let v132: i32 = i32(_lid.x);
        let v133: i32 = v132 & 127;
        let v134: i32 = i32(u32(v133) % u32(32));
        let v135: i32 = i32(_lid.x);
        let v136: i32 = i32(u32(v135) / u32(32));
        let v137: i32 = v134 << u32(0);
        let v138: i32 = 0 | v137;
        let v139: i32 = v136 << u32(5);
        let v140: i32 = v138 | v139;
        let v141: i32 = v140 & 127;
        let v142: i32 = i32(u32(v141) >> u32(0));
        let v143: i32 = v142 | 0;
        let v144: i32 = 0 ^ v143;
        let v145: i32 = v144 ^ 0;
        let v146: i32 = v145 + 0;
        let v147: i32 = v131 + v146;
        let v148: bool = v147 < params.N;
        let v149: i32 = v11 * params.stride;
        let v152: f32 = buf0[u32((v149 + v147))];
        let v153: f32 = select(f32(0.0), v152, v148);
        let v155: f32 = buf3[u32(v147)];
        let v156: f32 = select(f32(1.0), v155, v148);
        let v159: f32 = v153 * v126;
        let v160: f32 = v159 * v156;
        let v161: f32 = select(f32(0), v160, v148);
        if v148 { buf2[u32((v149 + v147))] = v161; }
        let v162: i32 = v128 + 1;
        v128 = v162;
    }
    if _lid.x == 0u { buf4[u32(v11)] = v126; }
}
